# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Deploy to TestFlight"
  lane :beta do
    sync_code_signing(type: "appstore") # see code signing guide for more info
    build_app(scheme: "WeatherKitDemo")
    upload_to_testflight
  end

  # This fails and I don't know why.
  # The same tests pass when run from Xcode.
  desc "Run all tests"
  lane :tests do
    run_tests(
      devices: ["iPhone 14 Pro"],
      scheme: "WeatherKitDemo"
    )
  end

  desc "Generate localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "ScreenshotTests")
    # upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end
end
