# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Automatically creates a signing certificate and provisioning profile"
  lane :certs do
    get_certificates(development: true)
    get_provisioning_profile(development: true)
  end

  desc "Runs all unit and UI tests"
  # This works despite warnings that say
  # "deviceType from ... was NULL when -platform called".
  lane :tests do
    run_tests(
      devices: ["iPhone 14 Pro"],
      scheme: "WeatherKitDemo"
    )
  end

  desc "Generates localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "ScreenshotTests")
  end

  desc "Creates new screenshots from existing ones that have device frames"
  # The PNG files this produces have sizes that App Store doesn't accept!
  # See https://github.com/fastlane/fastlane/issues/21067.
  lane :frames do
    frame_screenshots(is_complex_framing_mode: true)
  end

  desc "Uploads localized screenshots to App Store"
  # I needed to rename the "hi-IN" directory to "hi"
  # and the "zh-CN" directory to "zh-Hans".
  lane :upload do
    # Only uploading screenshots.
    upload_to_app_store(
      skip_app_version_update: true,
      skip_binary_upload: true,
      skip_metadata: true
    )
  end

  desc "Builds the app and produces symbol and ipa files."
  lane :build do
    build_app
  end

  desc "Deploys app to TestFlight"
  # THIS DOES NOT WORK!
  lane :beta do
    # increment_build_number # NOT WORKING!
    # increment_version_number(bump_type: "patch") # NOT WORKING!
    upload_to_testflight(
      ipa: './fastlane/builds/WeatherKitDemo.ipa',
      skip_submission: true
    )
  end

end
