# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :ios

platform :ios do

  desc "Runs all unit and UI tests"
  # This works despite warnings that say
  # "deviceType from ... was NULL when -platform called".
  lane :tests do
    run_tests(
      devices: ["iPhone 8 Plus", "iPhone 13 Pro Max"],
      scheme: "WeatherKitDemo"
    )
  end

  desc "Creates a signing certificate and provisioning profile"
  lane :certs do
    get_certificates(development: true)
    get_provisioning_profile(development: true)
  end

  desc "Builds the app and produces symbol and ipa files."
  lane :build do
    build_app
  end

  desc "Uploads the app to TestFlight"
  lane :beta do
    # I prefer to update the Version and Build numbers manually in Xcode.
    # increment_build_number
    # increment_version_number(bump_type: "patch")
    upload_to_testflight(
      ipa: './fastlane/builds/WeatherKitDemo.ipa',
      # I prefer to submit manually on the App Store Connect web page
      # so I can enter a description of what changed in this version.
      skip_submission: true
    )
  end

  desc "Generates localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "ScreenshotTests")
  end

  desc "Creates new screenshots from existing ones that have device frames"
  lane :frames do
    frame_screenshots
  end

  desc "Uploads localized screenshots to App Store"
  # I needed to rename the "hi-IN" directory to "hi"
  # and the "zh-CN" directory to "zh-Hans".
  lane :upload_screenshots do
    # Only uploading screenshots.
    upload_to_app_store(
      skip_app_version_update: true,
      skip_binary_upload: true,
      skip_metadata: true
    )
  end

  # Uploads the app to the App Store
  lane :prod do
    upload_to_app_store(
      ipa: './fastlane/builds/WeatherKitDemo.ipa', # in fastlane/builds
      # run_precheck_before_submit: false,
      skip_app_version_update: true,
      skip_binary_upload: true,
      skip_metadata: true,
      skip_screenshots: true
      # I prefer to submit manually on the App Store Connect web page
      # so I can enter a description of what changed in this version.
      # submit_for_review: true # defaults to false
    )
  end

  desc "Call Comet"
  lane :comet do
    say "Comet, wanna treat?"
  end
end

desc "Prints the version and build number"
lane :version do
  version = get_version_number
  build = get_build_number
  puts "version #{version}, build #{build}"
end
