# A list of devices you want to take the screenshots from
devices([
  # "iPhone 14"
  "iPhone 8 Plus",
  "iPhone 11 Pro Max",
  # "iPhone 13 Pro Max"
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "en-US", # English - USA
  "zh-CN", # Chinese Simplified - China
  "hi-IN", # Hindi - India
  "es-ES", # Spanish - Spain
  "fr-FR" # French - France
])

# The name of the scheme which contains the UI Tests
scheme("ScreenshotTests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

skip_open_summary(true)

headless(false) # This may be required for tests that use `waitForExistence`.

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
